export const pairs = [
    { id: "pipe", symbol: "%>%", meaning: "tidy. pipe" },
    { id: "equal", symbol: "==", meaning: "equality" },
    { id: "assign", symbol: "<-", meaning: "assign" },
    { id: "plus", symbol: "+", meaning: "add" },
    { id: "neq", symbol: "!=", meaning: "not equal" },
    { id: "comment", symbol: "#", meaning: "comment" },
    { id: "base", symbol: "|>", meaning: "base pipe" },
    { id: "mean", symbol: "mean()", meaning: "average" },
    { id: "sum", symbol: "sum()", meaning: "total" },
    { id: "median", symbol: "median()", meaning: "middle value" },
    { id: "sd", symbol: "sd()", meaning: "std deviation" },
    { id: "var", symbol: "var()", meaning: "variance" },
    { id: "quantile", symbol: "quantile()", meaning: "percentile" },
    { id: "length", symbol: "length()", meaning: "vector size" },
    { id: "nrow", symbol: "nrow()", meaning: "# of rows" },
    { id: "ncol", symbol: "ncol()", meaning: "# of columns" },
    { id: "unique", symbol: "unique()", meaning: "distinct values" },
    { id: "table", symbol: "table()", meaning: "freq table" },
    { id: "filter", symbol: "filter()", meaning: "subset rows" },
    { id: "mutate", symbol: "mutate()", meaning: "new column" },
    { id: "arrange", symbol: "arrange()", meaning: "sort rows" },
    { id: "select", symbol: "select()", meaning: "choose columns" },
    { id: "group_by", symbol: "group_by()", meaning: "group data" },
    { id: "summarise", symbol: "summarise()", meaning: "aggregate" },
    { id: "ggplot", symbol: "ggplot()", meaning: "plot data" },
    { id: "aes", symbol: "aes()", meaning: "map aesthetics" },
    { id: "geom_point", symbol: "geom_point()", meaning: "scatterplot" },
    { id: "geom_bar", symbol: "geom_bar()", meaning: "bar chart" },
    { id: "ifelse", symbol: "ifelse()", meaning: "conditional" },
    { id: "head", symbol: "head()", meaning: "first rows" },
    { id: "tail", symbol: "tail()", meaning: "last rows" },
    { id: "is.na", symbol: "is.na()", meaning: "is missing" },
    { id: "na.omit", symbol: "na.omit()", meaning: "remove NA" },
    { id: "paste", symbol: "paste()", meaning: "combine text" },
    { id: "str", symbol: "str()", meaning: "structure" },
    { id: "class", symbol: "class()", meaning: "data type" },
    { id: "typeof", symbol: "typeof()", meaning: "object type" },
    { id: "levels", symbol: "levels()", meaning: "factor levels" },
    { id: "rownames", symbol: "rownames()", meaning: "row names" },
    { id: "colnames", symbol: "colnames()", meaning: "col names" },
    { id: "cbind", symbol: "cbind()", meaning: "bind columns" },
    { id: "rbind", symbol: "rbind()", meaning: "bind rows" },
    { id: "rep", symbol: "rep()", meaning: "repeat" },
    { id: "seq", symbol: "seq()", meaning: "sequence" },
    { id: "factor", symbol: "factor()", meaning: "categorical" },
    { id: "as.numeric", symbol: "as.numeric()", meaning: "to numeric" },
    { id: "as.character", symbol: "as.character()", meaning: "to text" },
    { id: "as.factor", symbol: "as.factor()", meaning: "to factor" },
    { id: "cor", symbol: "cor()", meaning: "correlation" },
    { id: "lm", symbol: "lm()", meaning: "linear model" },
    { id: "anova", symbol: "anova()", meaning: "ANOVA test" },
    { id: "t.test", symbol: "t.test()", meaning: "t-test" },
    { id: "chisq.test", symbol: "chisq.test()", meaning: "chi-square" },
    { id: "prop.test", symbol: "prop.test()", meaning: "prop test" },
    { id: "install.packages", symbol: "install.packages()", meaning: "install pkg" },
    { id: "library", symbol: "library()", meaning: "load pkg" }
];
